name: Deploy Maven Repository into GitHub Pages
on:
  release:
    types: [ published ]
permissions:
  pull-requests: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: checkout pages branch
        uses: actions/checkout@v4
        with:
          path: pages
          ref: pages
          fetch-depth: 0
      - name: deploy
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: pages
          add-paths: maven-repo
          branch: mvn-repo/patch
          branch-suffix: timestamp
          commit-message: update maven repository
          title: '[AUTO] Update Maven Repository in GitHub Pages'
          body: auto-generated by Github Workflow
